# Generated by Django 2.1.5 on 2020-08-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='analysis',
            name='imagefile',
            field=models.FileField(null=True, upload_to='images/', verbose_name='img'),
        ),
    ]
