# Generated by Django 2.1.5 on 2020-08-26 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20200808_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='imagefile',
            field=models.FileField(null=True, upload_to='', verbose_name='img'),
        ),
    ]
