# Generated by Django 2.1.5 on 2020-08-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20200826_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='title',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
